import { lusitana } from '@/app/ui/fonts'; // フォントのインポート

export default function LEDcontent() {
  return (
    <div className="flex flex-col gap-4 p-6">
      <h2 className="text-xl font-bold text-gray-800">LED</h2>
      <p className={`${lusitana.className} text-lg text-gray-600`}>
       LEDは以下のように接続します。っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       LEDは以下のように接続します。っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       LEDは以下のように接続します。っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       LEDは以下のように接続します。っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
       っっっっっっっじょっっっっっっっっっっっ
       っっっっっっっっっっっっっっっっっっっっっlっっっっjっfあああIfjl感vじゃんvk
       gohaoivnkvnkjvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
      </p>
    </div>
  );
}